'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3603
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization
<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://services.bacardi.com", ClrNamespace:="services.bacardi.com")> 

Namespace BacardiWS.DMS

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceCredentials", [Namespace]:="https://services.bacardi.com")> _
    Partial Public Class ServiceCredentials
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private AppIDField As Integer

        Private SOAPKeyField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property AppID() As Integer
            Get
                Return Me.AppIDField
            End Get
            Set(ByVal value As Integer)
                Me.AppIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property SOAPKey() As String
            Get
                Return Me.SOAPKeyField
            End Get
            Set(ByVal value As String)
                Me.SOAPKeyField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="DMSReport", [Namespace]:="https://services.bacardi.com")> _
    Partial Public Class DMSReport
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private BrandMetricsField() As BacardiWS.DMS.DMSReportItem

        Private CampaignIdField As Integer

        Private CampaignMetricsField() As BacardiWS.DMS.DMSReportItem

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property BrandMetrics() As BacardiWS.DMS.DMSReportItem()
            Get
                Return Me.BrandMetricsField
            End Get
            Set(ByVal value As BacardiWS.DMS.DMSReportItem())
                Me.BrandMetricsField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignId() As Integer
            Get
                Return Me.CampaignIdField
            End Get
            Set(ByVal value As Integer)
                Me.CampaignIdField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignMetrics() As BacardiWS.DMS.DMSReportItem()
            Get
                Return Me.CampaignMetricsField
            End Get
            Set(ByVal value As BacardiWS.DMS.DMSReportItem())
                Me.CampaignMetricsField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="DMSReportItem", [Namespace]:="https://services.bacardi.com")> _
    Partial Public Class DMSReportItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private MetricNameField As String

        Private MetricValueField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MetricName() As String
            Get
                Return Me.MetricNameField
            End Get
            Set(ByVal value As String)
                Me.MetricNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MetricValue() As String
            Get
                Return Me.MetricValueField
            End Get
            Set(ByVal value As String)
                Me.MetricValueField = value
            End Set
        End Property
    End Class
End Namespace

Namespace Bacardi.DMS.Core.Interfaces

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsumerProfile", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces"), _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Bacardi.DMS.Core.Interfaces.FullConsumerProfile))> _
    Partial Public Class ConsumerProfile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private Address1Field As String

        Private Address2Field As String

        Private Address3Field As String

        Private CityField As String

        Private ConsumerIDField As Integer

        Private CountryField As String

        Private CountyField As String

        Private DateAddedField As Date

        Private DateModifiedField As Date

        Private DateOfBirthField As Date

        Private EmailField As String

        Private EmailOptInField As Boolean

        Private FirstNameField As String

        Private GenderField As Bacardi.DMS.Core.Interfaces.ConsumerGender

        Private LastNameField As String

        Private MiddleNameField As String

        Private MobileField As String

        Private MobileOptInField As Boolean

        Private Phone1Field As String

        Private Phone2Field As String

        Private PostalCodeField As String

        Private PostalOptInField As Boolean

        Private StateProvinceField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Address1() As String
            Get
                Return Me.Address1Field
            End Get
            Set(ByVal value As String)
                Me.Address1Field = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Address2() As String
            Get
                Return Me.Address2Field
            End Get
            Set(ByVal value As String)
                Me.Address2Field = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Address3() As String
            Get
                Return Me.Address3Field
            End Get
            Set(ByVal value As String)
                Me.Address3Field = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set(ByVal value As String)
                Me.CityField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ConsumerID() As Integer
            Get
                Return Me.ConsumerIDField
            End Get
            Set(ByVal value As Integer)
                Me.ConsumerIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set(ByVal value As String)
                Me.CountryField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property County() As String
            Get
                Return Me.CountyField
            End Get
            Set(ByVal value As String)
                Me.CountyField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property DateAdded() As Date
            Get
                Return Me.DateAddedField
            End Get
            Set(ByVal value As Date)
                Me.DateAddedField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property DateModified() As Date
            Get
                Return Me.DateModifiedField
            End Get
            Set(ByVal value As Date)
                Me.DateModifiedField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property DateOfBirth() As Date
            Get
                Return Me.DateOfBirthField
            End Get
            Set(ByVal value As Date)
                Me.DateOfBirthField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set(ByVal value As String)
                Me.EmailField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property EmailOptIn() As Boolean
            Get
                Return Me.EmailOptInField
            End Get
            Set(ByVal value As Boolean)
                Me.EmailOptInField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set(ByVal value As String)
                Me.FirstNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Gender() As Bacardi.DMS.Core.Interfaces.ConsumerGender
            Get
                Return Me.GenderField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.ConsumerGender)
                Me.GenderField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set(ByVal value As String)
                Me.LastNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MiddleName() As String
            Get
                Return Me.MiddleNameField
            End Get
            Set(ByVal value As String)
                Me.MiddleNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Mobile() As String
            Get
                Return Me.MobileField
            End Get
            Set(ByVal value As String)
                Me.MobileField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MobileOptIn() As Boolean
            Get
                Return Me.MobileOptInField
            End Get
            Set(ByVal value As Boolean)
                Me.MobileOptInField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Phone1() As String
            Get
                Return Me.Phone1Field
            End Get
            Set(ByVal value As String)
                Me.Phone1Field = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Phone2() As String
            Get
                Return Me.Phone2Field
            End Get
            Set(ByVal value As String)
                Me.Phone2Field = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set(ByVal value As String)
                Me.PostalCodeField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PostalOptIn() As Boolean
            Get
                Return Me.PostalOptInField
            End Get
            Set(ByVal value As Boolean)
                Me.PostalOptInField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property StateProvince() As String
            Get
                Return Me.StateProvinceField
            End Get
            Set(ByVal value As String)
                Me.StateProvinceField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="FullConsumerProfile", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class FullConsumerProfile
        Inherits Bacardi.DMS.Core.Interfaces.ConsumerProfile

        Private CampaignCustomFieldDataField() As Bacardi.DMS.Core.Interfaces.CustomFieldData

        Private ConsumerInterestsField() As Bacardi.DMS.Core.Interfaces.ConsumerInterest

        Private ConsumerPreferencesField() As Bacardi.DMS.Core.Interfaces.Preference

        Private MarketingQuestionAnswersField() As Bacardi.DMS.Core.Interfaces.MarketingQuestionAnswerData

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignCustomFieldData() As Bacardi.DMS.Core.Interfaces.CustomFieldData()
            Get
                Return Me.CampaignCustomFieldDataField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.CustomFieldData())
                Me.CampaignCustomFieldDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ConsumerInterests() As Bacardi.DMS.Core.Interfaces.ConsumerInterest()
            Get
                Return Me.ConsumerInterestsField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.ConsumerInterest())
                Me.ConsumerInterestsField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ConsumerPreferences() As Bacardi.DMS.Core.Interfaces.Preference()
            Get
                Return Me.ConsumerPreferencesField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.Preference())
                Me.ConsumerPreferencesField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MarketingQuestionAnswers() As Bacardi.DMS.Core.Interfaces.MarketingQuestionAnswerData()
            Get
                Return Me.MarketingQuestionAnswersField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.MarketingQuestionAnswerData())
                Me.MarketingQuestionAnswersField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsumerGender", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum ConsumerGender As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        NA = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        Female = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        Male = 2
    End Enum

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomFieldData", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class CustomFieldData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CampaignCustomFieldIDField As Integer

        Private CreateDateField As Date

        Private FieldNameField As String

        Private FieldValueField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignCustomFieldID() As Integer
            Get
                Return Me.CampaignCustomFieldIDField
            End Get
            Set(ByVal value As Integer)
                Me.CampaignCustomFieldIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FieldName() As String
            Get
                Return Me.FieldNameField
            End Get
            Set(ByVal value As String)
                Me.FieldNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FieldValue() As String
            Get
                Return Me.FieldValueField
            End Get
            Set(ByVal value As String)
                Me.FieldValueField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsumerInterest", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class ConsumerInterest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CreateDateField As Date

        Private InterestTextField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property InterestText() As String
            Get
                Return Me.InterestTextField
            End Get
            Set(ByVal value As String)
                Me.InterestTextField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="Preference", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class Preference
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CreateDateField As Date

        Private ModifyDateField As Date

        Private PreferenceNameField As String

        Private PreferenceValueField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ModifyDate() As Date
            Get
                Return Me.ModifyDateField
            End Get
            Set(ByVal value As Date)
                Me.ModifyDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PreferenceName() As String
            Get
                Return Me.PreferenceNameField
            End Get
            Set(ByVal value As String)
                Me.PreferenceNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PreferenceValue() As String
            Get
                Return Me.PreferenceValueField
            End Get
            Set(ByVal value As String)
                Me.PreferenceValueField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="MarketingQuestionAnswerData", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class MarketingQuestionAnswerData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private AnswerTextField As String

        Private CampignIDField As Integer

        Private CreateDateField As Date

        Private MarketingQuestionIDField As Integer

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property AnswerText() As String
            Get
                Return Me.AnswerTextField
            End Get
            Set(ByVal value As String)
                Me.AnswerTextField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampignID() As Integer
            Get
                Return Me.CampignIDField
            End Get
            Set(ByVal value As Integer)
                Me.CampignIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MarketingQuestionID() As Integer
            Get
                Return Me.MarketingQuestionIDField
            End Get
            Set(ByVal value As Integer)
                Me.MarketingQuestionIDField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="OptinType", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum OptinType As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        EmailOptin = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        MobileOptin = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        PostalOptin = 2
    End Enum

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsumerSourceType", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum ConsumerSourceType As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        WebsiteOptInForm = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        WebsiteConsumerFeedbackForm = 2

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        WebsiteCompetitionForm = 3

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        MobileSource = 4

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        ExternalOnlineSource = 5

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OfflineVisitorCenter = 6

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OfflineEvent = 7

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OfflineThirdPartySource = 8

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        WebsiteRegistrationForm = 10
    End Enum

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddConsumerProfileResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class AddConsumerProfileResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private NewConsumerIDField As Integer

        Private ResponseMessageField As Bacardi.DMS.Core.Interfaces.AddConsumerProfileMessage

        Private SuccessFlagField As Boolean

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property NewConsumerID() As Integer
            Get
                Return Me.NewConsumerIDField
            End Get
            Set(ByVal value As Integer)
                Me.NewConsumerIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ResponseMessage() As Bacardi.DMS.Core.Interfaces.AddConsumerProfileMessage
            Get
                Return Me.ResponseMessageField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.AddConsumerProfileMessage)
                Me.ResponseMessageField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property SuccessFlag() As Boolean
            Get
                Return Me.SuccessFlagField
            End Get
            Set(ByVal value As Boolean)
                Me.SuccessFlagField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddConsumerProfileMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum AddConsumerProfileMessage As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OK = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidCampaign = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        ConsumerAlreadyExists = 2

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        ConsumerExistsAndWasAddedToCampaign = 3

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidEmail = 4

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidDateOfBirth = 5

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        NeedToOptIn = 6

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidGender = 7

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        SiteCampaignMismatch = 8

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        [Error] = 9
    End Enum

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomField", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class CustomField
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CampaignCustomFieldIDField As Integer

        Private CreateDateField As Date

        Private FieldNameField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignCustomFieldID() As Integer
            Get
                Return Me.CampaignCustomFieldIDField
            End Get
            Set(ByVal value As Integer)
                Me.CampaignCustomFieldIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FieldName() As String
            Get
                Return Me.FieldNameField
            End Get
            Set(ByVal value As String)
                Me.FieldNameField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="MarketingQuestion", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class MarketingQuestion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private AllowFreeTextAnswerField As Boolean

        Private AllowMultipleAnswersField As Boolean

        Private FullQuestionTextField As String

        Private IsMultipleChoiceField As Boolean

        Private MarketingQuestionIDField As Integer

        Private QuestionChoicesField() As String

        Private QuestionNameField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property AllowFreeTextAnswer() As Boolean
            Get
                Return Me.AllowFreeTextAnswerField
            End Get
            Set(ByVal value As Boolean)
                Me.AllowFreeTextAnswerField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property AllowMultipleAnswers() As Boolean
            Get
                Return Me.AllowMultipleAnswersField
            End Get
            Set(ByVal value As Boolean)
                Me.AllowMultipleAnswersField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FullQuestionText() As String
            Get
                Return Me.FullQuestionTextField
            End Get
            Set(ByVal value As String)
                Me.FullQuestionTextField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property IsMultipleChoice() As Boolean
            Get
                Return Me.IsMultipleChoiceField
            End Get
            Set(ByVal value As Boolean)
                Me.IsMultipleChoiceField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MarketingQuestionID() As Integer
            Get
                Return Me.MarketingQuestionIDField
            End Get
            Set(ByVal value As Integer)
                Me.MarketingQuestionIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property QuestionChoices() As String()
            Get
                Return Me.QuestionChoicesField
            End Get
            Set(ByVal value As String())
                Me.QuestionChoicesField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property QuestionName() As String
            Get
                Return Me.QuestionNameField
            End Get
            Set(ByVal value As String)
                Me.QuestionNameField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsumerPreference", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class ConsumerPreference
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CreateDateField As Date

        Private ModifyDateField As Date

        Private PreferenceNameField As String

        Private PreferenceValueField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ModifyDate() As Date
            Get
                Return Me.ModifyDateField
            End Get
            Set(ByVal value As Date)
                Me.ModifyDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PreferenceName() As String
            Get
                Return Me.PreferenceNameField
            End Get
            Set(ByVal value As String)
                Me.PreferenceNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PreferenceValue() As String
            Get
                Return Me.PreferenceValueField
            End Get
            Set(ByVal value As String)
                Me.PreferenceValueField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResetConsumerPasswordResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class ResetConsumerPasswordResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private GeneratedPasswordField As String

        Private ResponseMessageField As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordMessage

        Private SuccessFlagField As Boolean

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property GeneratedPassword() As String
            Get
                Return Me.GeneratedPasswordField
            End Get
            Set(ByVal value As String)
                Me.GeneratedPasswordField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ResponseMessage() As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordMessage
            Get
                Return Me.ResponseMessageField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordMessage)
                Me.ResponseMessageField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property SuccessFlag() As Boolean
            Get
                Return Me.SuccessFlagField
            End Get
            Set(ByVal value As Boolean)
                Me.SuccessFlagField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResetConsumerPasswordMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum ResetConsumerPasswordMessage As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OK = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidConsumer = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        PasswordTooShort = 2
    End Enum

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateConsumerProfileResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class UpdateConsumerProfileResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private ResponseMessageField As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileMessage

        Private SuccessFlagField As Boolean

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property ResponseMessage() As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileMessage
            Get
                Return Me.ResponseMessageField
            End Get
            Set(ByVal value As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileMessage)
                Me.ResponseMessageField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property SuccessFlag() As Boolean
            Get
                Return Me.SuccessFlagField
            End Get
            Set(ByVal value As Boolean)
                Me.SuccessFlagField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateConsumerProfileMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Public Enum UpdateConsumerProfileMessage As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OK = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidConsumer = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidDateOfBirth = 2

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        [Error] = 3
    End Enum

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="Campaign", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Interfaces")> _
    Partial Public Class Campaign
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private CampaignDescriptionField As String

        Private CampaignIDField As Integer

        Private CampaignNameField As String

        Private CampaignTypeIDField As Integer

        Private CreateDateField As Date

        Private CreatedByField As String

        Private IsActiveField As Boolean

        Private MarketIDField As Integer

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignDescription() As String
            Get
                Return Me.CampaignDescriptionField
            End Get
            Set(ByVal value As String)
                Me.CampaignDescriptionField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignID() As Integer
            Get
                Return Me.CampaignIDField
            End Get
            Set(ByVal value As Integer)
                Me.CampaignIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignName() As String
            Get
                Return Me.CampaignNameField
            End Get
            Set(ByVal value As String)
                Me.CampaignNameField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CampaignTypeID() As Integer
            Get
                Return Me.CampaignTypeIDField
            End Get
            Set(ByVal value As Integer)
                Me.CampaignTypeIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set(ByVal value As Date)
                Me.CreateDateField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set(ByVal value As String)
                Me.CreatedByField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property IsActive() As Boolean
            Get
                Return Me.IsActiveField
            End Get
            Set(ByVal value As Boolean)
                Me.IsActiveField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property MarketID() As Integer
            Get
                Return Me.MarketIDField
            End Get
            Set(ByVal value As Integer)
                Me.MarketIDField = value
            End Set
        End Property
    End Class
End Namespace

Namespace Bacardi.DMS.Core.Remote

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="CampaignFieldDataResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Remote")> _
    Public Enum CampaignFieldDataResponse As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OK = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidConsumer = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidCampaignCustomField = 2

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        ConsumerIsNotInCampaign = 3
    End Enum

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="AddMarketingQuestionResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Bacardi.DMS.Core.Remote")> _
    Public Enum AddMarketingQuestionResponse As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        OK = 0

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidConsumer = 1

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidMarketingQuestionID = 2

        <System.Runtime.Serialization.EnumMemberAttribute()> _
        InvalidCampaign = 3
    End Enum
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="https://services.bacardi.com", ConfigurationName:="IDMSService")> _
Public Interface IDMSService

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerProfileInBrand_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerProfileInBrand_1Response")> _
    Function GetConsumerProfileInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal brandId As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerProfileByConsumerIDInBrand_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerProfileByConsumerIDInBrand_1R" & _
        "esponse")> _
    Function GetConsumerProfileByConsumerIDInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal brandId As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/CheckConsumerOptin_1", ReplyAction:="https://services.bacardi.com/IDMSService/CheckConsumerOptin_1Response")> _
    Function CheckConsumerOptin_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/CheckConsumerOptout_1", ReplyAction:="https://services.bacardi.com/IDMSService/CheckConsumerOptout_1Response")> _
    Function CheckConsumerOptout_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/OptinConsumerForCampaign_1", ReplyAction:="https://services.bacardi.com/IDMSService/OptinConsumerForCampaign_1Response")> _
    Function OptinConsumerForCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/OptoutConsumerForCampaign_1", ReplyAction:="https://services.bacardi.com/IDMSService/OptoutConsumerForCampaign_1Response")> _
    Function OptoutConsumerForCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/SetCampaignFieldValue_1", ReplyAction:="https://services.bacardi.com/IDMSService/SetCampaignFieldValue_1Response")> _
    Function SetCampaignFieldValue_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal customFieldID As Integer, ByVal customFieldValue As String) As Bacardi.DMS.Core.Remote.CampaignFieldDataResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/SetConsumerInterest_1", ReplyAction:="https://services.bacardi.com/IDMSService/SetConsumerInterest_1Response")> _
    Function SetConsumerInterest_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal interest As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/DeleteConsumerRecord_1", ReplyAction:="https://services.bacardi.com/IDMSService/DeleteConsumerRecord_1Response")> _
    Function DeleteConsumerRecord_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/CheckValidCampaign_1", ReplyAction:="https://services.bacardi.com/IDMSService/CheckValidCampaign_1Response")> _
    Function CheckValidCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/AddConsumerProfile_1", ReplyAction:="https://services.bacardi.com/IDMSService/AddConsumerProfile_1Response")> _
    Function AddConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile, ByVal sourceCampaignID As Integer, ByVal source As Bacardi.DMS.Core.Interfaces.ConsumerSourceType, ByVal addConsumerToCampaignIfEmailAlreadyExists As Boolean, ByVal newPassword As String) As Bacardi.DMS.Core.Interfaces.AddConsumerProfileResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/AddConsumerToCampaign_1", ReplyAction:="https://services.bacardi.com/IDMSService/AddConsumerToCampaign_1Response")> _
    Function AddConsumerToCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal campaignID As Integer) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/SetMarketingQuestionAnswer_1", ReplyAction:="https://services.bacardi.com/IDMSService/SetMarketingQuestionAnswer_1Response")> _
    Function SetMarketingQuestionAnswer_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal campaignID As Integer, ByVal marketingQuestionID As Integer, ByVal answerText As String) As Bacardi.DMS.Core.Remote.AddMarketingQuestionResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/CheckConsumerLogin_1", ReplyAction:="https://services.bacardi.com/IDMSService/CheckConsumerLogin_1Response")> _
    Function CheckConsumerLogin_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal email As String, ByVal password As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/CheckConsumerLoginInBrand_1", ReplyAction:="https://services.bacardi.com/IDMSService/CheckConsumerLoginInBrand_1Response")> _
    Function CheckConsumerLoginInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal email As String, ByVal password As String, ByVal randId As Integer) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/DeleteConsumerInterest_1", ReplyAction:="https://services.bacardi.com/IDMSService/DeleteConsumerInterest_1Response")> _
    Function DeleteConsumerInterest_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal interest As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/DeleteConsumerPreference_1", ReplyAction:="https://services.bacardi.com/IDMSService/DeleteConsumerPreference_1Response")> _
    Function DeleteConsumerPreference_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal preferenceName As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetCampaignCustomFields_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetCampaignCustomFields_1Response")> _
    Function GetCampaignCustomFields_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Bacardi.DMS.Core.Interfaces.CustomField()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetCampaignMarketingQuestions_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetCampaignMarketingQuestions_1Response")> _
    Function GetCampaignMarketingQuestions_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Bacardi.DMS.Core.Interfaces.MarketingQuestion()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerFullProfile_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerFullProfile_1Response")> _
    Function GetConsumerFullProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerFullProfileByConsumerID_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerFullProfileByConsumerID_1Resp" & _
        "onse")> _
    Function GetConsumerFullProfileByConsumerID_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerInterests_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerInterests_1Response")> _
    Function GetConsumerInterests_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerInterest()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerPreferences_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerPreferences_1Response")> _
    Function GetConsumerPreferences_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerPreference()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerProfile_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerProfile_1Response")> _
    Function GetConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerProfileByConsumerID_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerProfileByConsumerID_1Response" & _
        "")> _
    Function GetConsumerProfileByConsumerID_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/ResetConsumerPassword_1", ReplyAction:="https://services.bacardi.com/IDMSService/ResetConsumerPassword_1Response")> _
    Function ResetConsumerPassword_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal generatePassword As Boolean, ByVal newPassword As String) As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/ResetConsumerInBrandPassword_1", ReplyAction:="https://services.bacardi.com/IDMSService/ResetConsumerInBrandPassword_1Response")> _
    Function ResetConsumerInBrandPassword_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal generatePassword As Boolean, ByVal newPassword As String, ByVal brandID As Integer) As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/SetConsumerPreference_1", ReplyAction:="https://services.bacardi.com/IDMSService/SetConsumerPreference_1Response")> _
    Function SetConsumerPreference_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal preferenceName As String, ByVal preferenceValue As String) As Boolean

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/UpdateConsumerProfile_1", ReplyAction:="https://services.bacardi.com/IDMSService/UpdateConsumerProfile_1Response")> _
    Function UpdateConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile) As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/UpdateConsumerProfileInBrand_1", ReplyAction:="https://services.bacardi.com/IDMSService/UpdateConsumerProfileInBrand_1Response")> _
    Function UpdateConsumerProfileInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile, ByVal BrandId As Integer) As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileResponse

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerCampaignMembership_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerCampaignMembership_1Response")> _
    Function GetConsumerCampaignMembership_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.Campaign()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerCampaignMembership_2", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerCampaignMembership_2Response")> _
    Function GetConsumerCampaignMembership_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal includeOptout As Boolean) As Bacardi.DMS.Core.Interfaces.Campaign()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerInCampaignCount_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerInCampaignCount_1Response")> _
    Function GetConsumerInCampaignCount_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal startDate As Date, ByVal endDate As Date, ByVal campaignID As Integer) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerInCampaignCount_2", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerInCampaignCount_2Response")> _
    Function GetConsumerInCampaignCount_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal startDate As Date, ByVal endDate As Date, ByVal campaignID As Integer, ByVal includeOptout As Boolean) As Integer

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumersFromCampaign_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumersFromCampaign_1Response")> _
    Function GetConsumersFromCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal deepLoad As Boolean) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumersFromCampaign_2", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumersFromCampaign_2Response")> _
    Function GetConsumersFromCampaign_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal deepLoad As Boolean, ByVal includeOptout As Boolean) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile()

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerStatistics_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerStatistics_1Response")> _
    Function GetConsumerStatistics_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal includeAllBrandData As Boolean) As BacardiWS.DMS.DMSReport

    <System.ServiceModel.OperationContractAttribute(Action:="https://services.bacardi.com/IDMSService/GetConsumerStatisticsInDateRange_1", ReplyAction:="https://services.bacardi.com/IDMSService/GetConsumerStatisticsInDateRange_1Respon" & _
        "se")> _
    Function GetConsumerStatisticsInDateRange_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal includeAllBrandData As Boolean, ByVal startDate As Date, ByVal endDate As Date) As BacardiWS.DMS.DMSReport
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface IDMSServiceChannel
    Inherits IDMSService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class DMSServiceClient
    Inherits System.ServiceModel.ClientBase(Of IDMSService)
    Implements IDMSService

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Public Function GetConsumerProfileInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal brandId As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile Implements IDMSService.GetConsumerProfileInBrand_1
        Return MyBase.Channel.GetConsumerProfileInBrand_1(credentials, consumerEmail, brandId)
    End Function

    Public Function GetConsumerProfileByConsumerIDInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal brandId As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile Implements IDMSService.GetConsumerProfileByConsumerIDInBrand_1
        Return MyBase.Channel.GetConsumerProfileByConsumerIDInBrand_1(credentials, consumerID, brandId)
    End Function

    Public Function CheckConsumerOptin_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean Implements IDMSService.CheckConsumerOptin_1
        Return MyBase.Channel.CheckConsumerOptin_1(credentials, consumerID, campaignID, type)
    End Function

    Public Function CheckConsumerOptout_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean Implements IDMSService.CheckConsumerOptout_1
        Return MyBase.Channel.CheckConsumerOptout_1(credentials, consumerID, campaignID, type)
    End Function

    Public Function OptinConsumerForCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean Implements IDMSService.OptinConsumerForCampaign_1
        Return MyBase.Channel.OptinConsumerForCampaign_1(credentials, consumerID, campaignID, type)
    End Function

    Public Function OptoutConsumerForCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal campaignID As Integer, ByVal type As Bacardi.DMS.Core.Interfaces.OptinType) As Boolean Implements IDMSService.OptoutConsumerForCampaign_1
        Return MyBase.Channel.OptoutConsumerForCampaign_1(credentials, consumerID, campaignID, type)
    End Function

    Public Function SetCampaignFieldValue_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal customFieldID As Integer, ByVal customFieldValue As String) As Bacardi.DMS.Core.Remote.CampaignFieldDataResponse Implements IDMSService.SetCampaignFieldValue_1
        Return MyBase.Channel.SetCampaignFieldValue_1(credentials, consumerEmail, customFieldID, customFieldValue)
    End Function

    Public Function SetConsumerInterest_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal interest As String) As Boolean Implements IDMSService.SetConsumerInterest_1
        Return MyBase.Channel.SetConsumerInterest_1(credentials, consumerEmail, interest)
    End Function

    Public Function DeleteConsumerRecord_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Boolean Implements IDMSService.DeleteConsumerRecord_1
        Return MyBase.Channel.DeleteConsumerRecord_1(credentials, consumerEmail)
    End Function

    Public Function CheckValidCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Boolean Implements IDMSService.CheckValidCampaign_1
        Return MyBase.Channel.CheckValidCampaign_1(credentials, campaignID)
    End Function

    Public Function AddConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile, ByVal sourceCampaignID As Integer, ByVal source As Bacardi.DMS.Core.Interfaces.ConsumerSourceType, ByVal addConsumerToCampaignIfEmailAlreadyExists As Boolean, ByVal newPassword As String) As Bacardi.DMS.Core.Interfaces.AddConsumerProfileResponse Implements IDMSService.AddConsumerProfile_1
        Return MyBase.Channel.AddConsumerProfile_1(credentials, profile, sourceCampaignID, source, addConsumerToCampaignIfEmailAlreadyExists, newPassword)
    End Function

    Public Function AddConsumerToCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal campaignID As Integer) As Boolean Implements IDMSService.AddConsumerToCampaign_1
        Return MyBase.Channel.AddConsumerToCampaign_1(credentials, consumerEmail, campaignID)
    End Function

    Public Function SetMarketingQuestionAnswer_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal campaignID As Integer, ByVal marketingQuestionID As Integer, ByVal answerText As String) As Bacardi.DMS.Core.Remote.AddMarketingQuestionResponse Implements IDMSService.SetMarketingQuestionAnswer_1
        Return MyBase.Channel.SetMarketingQuestionAnswer_1(credentials, consumerEmail, campaignID, marketingQuestionID, answerText)
    End Function

    Public Function CheckConsumerLogin_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal email As String, ByVal password As String) As Boolean Implements IDMSService.CheckConsumerLogin_1
        Return MyBase.Channel.CheckConsumerLogin_1(credentials, email, password)
    End Function

    Public Function CheckConsumerLoginInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal email As String, ByVal password As String, ByVal randId As Integer) As Boolean Implements IDMSService.CheckConsumerLoginInBrand_1
        Return MyBase.Channel.CheckConsumerLoginInBrand_1(credentials, email, password, randId)
    End Function

    Public Function DeleteConsumerInterest_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal interest As String) As Boolean Implements IDMSService.DeleteConsumerInterest_1
        Return MyBase.Channel.DeleteConsumerInterest_1(credentials, consumerEmail, interest)
    End Function

    Public Function DeleteConsumerPreference_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal preferenceName As String) As Boolean Implements IDMSService.DeleteConsumerPreference_1
        Return MyBase.Channel.DeleteConsumerPreference_1(credentials, consumerEmail, preferenceName)
    End Function

    Public Function GetCampaignCustomFields_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Bacardi.DMS.Core.Interfaces.CustomField() Implements IDMSService.GetCampaignCustomFields_1
        Return MyBase.Channel.GetCampaignCustomFields_1(credentials, campaignID)
    End Function

    Public Function GetCampaignMarketingQuestions_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer) As Bacardi.DMS.Core.Interfaces.MarketingQuestion() Implements IDMSService.GetCampaignMarketingQuestions_1
        Return MyBase.Channel.GetCampaignMarketingQuestions_1(credentials, campaignID)
    End Function

    Public Function GetConsumerFullProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile Implements IDMSService.GetConsumerFullProfile_1
        Return MyBase.Channel.GetConsumerFullProfile_1(credentials, consumerEmail)
    End Function

    Public Function GetConsumerFullProfileByConsumerID_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile Implements IDMSService.GetConsumerFullProfileByConsumerID_1
        Return MyBase.Channel.GetConsumerFullProfileByConsumerID_1(credentials, consumerID)
    End Function

    Public Function GetConsumerInterests_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerInterest() Implements IDMSService.GetConsumerInterests_1
        Return MyBase.Channel.GetConsumerInterests_1(credentials, consumerEmail)
    End Function

    Public Function GetConsumerPreferences_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerPreference() Implements IDMSService.GetConsumerPreferences_1
        Return MyBase.Channel.GetConsumerPreferences_1(credentials, consumerEmail)
    End Function

    Public Function GetConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String) As Bacardi.DMS.Core.Interfaces.ConsumerProfile Implements IDMSService.GetConsumerProfile_1
        Return MyBase.Channel.GetConsumerProfile_1(credentials, consumerEmail)
    End Function

    Public Function GetConsumerProfileByConsumerID_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.ConsumerProfile Implements IDMSService.GetConsumerProfileByConsumerID_1
        Return MyBase.Channel.GetConsumerProfileByConsumerID_1(credentials, consumerID)
    End Function

    Public Function ResetConsumerPassword_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal generatePassword As Boolean, ByVal newPassword As String) As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordResponse Implements IDMSService.ResetConsumerPassword_1
        Return MyBase.Channel.ResetConsumerPassword_1(credentials, consumerEmail, generatePassword, newPassword)
    End Function

    Public Function ResetConsumerInBrandPassword_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal generatePassword As Boolean, ByVal newPassword As String, ByVal brandID As Integer) As Bacardi.DMS.Core.Interfaces.ResetConsumerPasswordResponse Implements IDMSService.ResetConsumerInBrandPassword_1
        Return MyBase.Channel.ResetConsumerInBrandPassword_1(credentials, consumerEmail, generatePassword, newPassword, brandID)
    End Function

    Public Function SetConsumerPreference_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerEmail As String, ByVal preferenceName As String, ByVal preferenceValue As String) As Boolean Implements IDMSService.SetConsumerPreference_1
        Return MyBase.Channel.SetConsumerPreference_1(credentials, consumerEmail, preferenceName, preferenceValue)
    End Function

    Public Function UpdateConsumerProfile_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile) As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileResponse Implements IDMSService.UpdateConsumerProfile_1
        Return MyBase.Channel.UpdateConsumerProfile_1(credentials, profile)
    End Function

    Public Function UpdateConsumerProfileInBrand_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal profile As Bacardi.DMS.Core.Interfaces.ConsumerProfile, ByVal BrandId As Integer) As Bacardi.DMS.Core.Interfaces.UpdateConsumerProfileResponse Implements IDMSService.UpdateConsumerProfileInBrand_1
        Return MyBase.Channel.UpdateConsumerProfileInBrand_1(credentials, profile, BrandId)
    End Function

    Public Function GetConsumerCampaignMembership_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer) As Bacardi.DMS.Core.Interfaces.Campaign() Implements IDMSService.GetConsumerCampaignMembership_1
        Return MyBase.Channel.GetConsumerCampaignMembership_1(credentials, consumerID)
    End Function

    Public Function GetConsumerCampaignMembership_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal consumerID As Integer, ByVal includeOptout As Boolean) As Bacardi.DMS.Core.Interfaces.Campaign() Implements IDMSService.GetConsumerCampaignMembership_2
        Return MyBase.Channel.GetConsumerCampaignMembership_2(credentials, consumerID, includeOptout)
    End Function

    Public Function GetConsumerInCampaignCount_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal startDate As Date, ByVal endDate As Date, ByVal campaignID As Integer) As Integer Implements IDMSService.GetConsumerInCampaignCount_1
        Return MyBase.Channel.GetConsumerInCampaignCount_1(credentials, startDate, endDate, campaignID)
    End Function

    Public Function GetConsumerInCampaignCount_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal startDate As Date, ByVal endDate As Date, ByVal campaignID As Integer, ByVal includeOptout As Boolean) As Integer Implements IDMSService.GetConsumerInCampaignCount_2
        Return MyBase.Channel.GetConsumerInCampaignCount_2(credentials, startDate, endDate, campaignID, includeOptout)
    End Function

    Public Function GetConsumersFromCampaign_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal deepLoad As Boolean) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile() Implements IDMSService.GetConsumersFromCampaign_1
        Return MyBase.Channel.GetConsumersFromCampaign_1(credentials, campaignID, deepLoad)
    End Function

    Public Function GetConsumersFromCampaign_2(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal deepLoad As Boolean, ByVal includeOptout As Boolean) As Bacardi.DMS.Core.Interfaces.FullConsumerProfile() Implements IDMSService.GetConsumersFromCampaign_2
        Return MyBase.Channel.GetConsumersFromCampaign_2(credentials, campaignID, deepLoad, includeOptout)
    End Function

    Public Function GetConsumerStatistics_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal includeAllBrandData As Boolean) As BacardiWS.DMS.DMSReport Implements IDMSService.GetConsumerStatistics_1
        Return MyBase.Channel.GetConsumerStatistics_1(credentials, campaignID, includeAllBrandData)
    End Function

    Public Function GetConsumerStatisticsInDateRange_1(ByVal credentials As BacardiWS.DMS.ServiceCredentials, ByVal campaignID As Integer, ByVal includeAllBrandData As Boolean, ByVal startDate As Date, ByVal endDate As Date) As BacardiWS.DMS.DMSReport Implements IDMSService.GetConsumerStatisticsInDateRange_1
        Return MyBase.Channel.GetConsumerStatisticsInDateRange_1(credentials, campaignID, includeAllBrandData, startDate, endDate)
    End Function
End Class
