<?
include_once("../php/inc/funciones.inc.php");
include_once("../php/inc/xml.inc.php");
include_once("../php/inc/input_class.php");
include_once("../php/inc/persistent.php");
include_once("../php/inc/est.php");
include_once("../php/inc/includes_php_mailer/class.phpmailer.php");
include_once("../php/inc/includes_php_mailer/class.smtp.php");
?>